<h1>Импорт библиотек

In [2]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [3]:
def sum_prod(X, V):
    '''
    X - матрицы (n, n)
    V - векторы (n, 1)
    Гарантируется, что len(X) == len(V)
    '''
    # Your code goes here
    result = 0
    for matrix, vector in zip(X, V):
        result += np.dot(matrix, vector).flatten()[0]
    return result
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
vector1 = np.array([[1], [2]])
vector2 = np.array([[3], [4]])
print(sum_prod([matrix1, matrix2], [vector1, vector2]))

44


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [4]:
def binarize(M, threshold=0.5):
    # Your code goes here
    binary_matrix = np.where(M > threshold, 1, 0)
    return binary_matrix
M = np.array([[0.2, 0.7, 0.9],
              [0.3, 0.6, 0.8],
              [0.1, 0.4, 0.5]])
print(binarize(M))

[[0 1 1]
 [0 1 1]
 [0 0 0]]


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [12]:
import numpy as np
def unique_elements_in_rows(matrix):
    unique_rows = [np.unique(row) for row in matrix]
    return unique_rows

print(unique_elements_in_rows([[1, 1, 3],
                       [4, 4, 6],
                       [1, 2, 3],
                       [4, 5, 6]]))

[array([1, 3]), array([4, 6]), array([1, 2, 3]), array([4, 5, 6])]


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
# Your code goes here

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [8]:
def chess(m, n, a, b):
    if m % 2 != 0:
        raise ValueError('Строки нечетные')
    if n % 2 != 0:
        raise ValueError('Столбцы нечетные')

    board = np.zeros((m,n), dtype = int)
    for i in range(m):
        for j in range(n):
            if (i+j) % 2 == 0:
                board[i, j] = a
            else: board[i,j] = b
    return board
print(chess(4,4,2,3))
print(chess(5,5,3,2))

[[2 3 2 3]
 [3 2 3 2]
 [2 3 2 3]
 [3 2 3 2]]


ValueError: Строки нечетные

<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [1]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
# Your code goes here